name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and run test in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: python -m pytest
